### ISSUE TITLE
File Gradle

### ISSUE THREAD

**Issue by rbtluisenriquerbt** [culqi/culqi-android#4]
Estimados, 

Podrían agregar el gradle? Estuve probando la pasarela pero al parecer las librerías que uso no son exactamente las que se usa para esto. 

Uso todo esto:

compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile 'com.android.support:support-v4:24.2.1'
    compile 'com.google.android.gms:play-services:9.4.0'
    compile 'com.android.support:support-v4:24.2.0'
    compile 'com.android.support:recyclerview-v7:24.2.0'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'org.codehaus.jackson:jackson-mapper-asl:1.9.12'
    compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'

Además, del legacy:

useLibrary 'org.apache.http.legacy'

**Comment by marti1125** [comment]
Hola @rbtluisenriquerbt vamos a rehacer este proyecto desde 0 :+1: 
alguna otra duda para cerrar este issue =?
