### ISSUE TITLE
Create Token

### ISSUE THREAD

**Issue by sonukavya** [culqi/culqi-android#8]
Hello dear
 i import project in android studio and try to create token with api key "pk_test_bZvlB0tvWZx53KE0"
 but we get auth error . so plz help me for solve this problem.

{"object": "error","type": "authentication_error","merchant_message": "Tu código de comercio no está habilitado para realizar este tipo de peticiones. Contáctate con soporte@culqi.com para obtener mas información."}
i hope you understand my  problem thank very much.

**Comment by joelibaceta** [comment]
duplicate https://github.com/culqi/culqi-android/issues/9
